# Generated by Django 3.1.4 on 2021-01-02 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('currentAmount', models.IntegerField()),
                ('creDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderDate', models.CharField(max_length=20)),
                ('deliveryDate', models.CharField(max_length=100)),
                ('creDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('creDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFM',
            fields=[
                ('time', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('recency', models.DateTimeField()),
                ('frequency', models.CharField(max_length=20)),
                ('monetaryValue', models.IntegerField()),
                ('creDate', models.DateTimeField(auto_now_add=True)),
                ('storeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=20)),
                ('EXP', models.CharField(max_length=100)),
                ('creDate', models.DateTimeField(auto_now_add=True)),
                ('productInventoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.inventory')),
                ('productOrderId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='storeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store'),
        ),
        migrations.CreateModel(
            name='LTV',
            fields=[
                ('time', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SCR', models.CharField(max_length=20)),
                ('SW', models.CharField(max_length=20)),
                ('sizeOfWallet', models.CharField(max_length=20)),
                ('creDate', models.DateTimeField(auto_now_add=True)),
                ('storeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='CAI',
            fields=[
                ('time', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('AIT', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('retentionRate', models.CharField(max_length=20)),
                ('survivalRate', models.CharField(max_length=20)),
                ('activeProbability', models.CharField(max_length=20)),
                ('creDate', models.DateTimeField(auto_now_add=True)),
                ('storeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
    ]
