# Generated by Django 3.1.4 on 2021-01-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='EXP',
            field=models.DateField(),
        ),
    ]
