# Generated by Django 3.1.4 on 2021-03-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '__first__'),
        ('material', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productionDate', models.DateField()),
                ('creDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('creDate', models.DateTimeField(auto_now_add=True)),
                ('productInventoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.inventory')),
                ('productionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.production')),
            ],
        ),
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costAmount', models.IntegerField()),
                ('creDate', models.DateTimeField(auto_now_add=True)),
                ('materialInventoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.inventory')),
                ('productionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.production')),
            ],
        ),
    ]
