# Generated by Django 3.1.4 on 2021-03-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('currentAmount', models.IntegerField()),
                ('creDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('purchaseDate', models.DateField()),
                ('creDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('creDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField()),
                ('price', models.IntegerField()),
                ('origin', models.CharField(max_length=100)),
                ('EXP', models.DateField()),
                ('creDate', models.DateTimeField(auto_now_add=True)),
                ('materialInventoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.inventory')),
                ('materialOrderId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='supplierId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.supplier'),
        ),
    ]
