name: Cloud Run-dev

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.DEV_RUN_PROJECT }}
  RUN_REGION: asia-east1
  SERVICE_NAME: feifeisocute

jobs:
  setup-build-deploy:
    name: dev
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.DEV_RUN_SA_KEY }}
        project_id: ${{ secrets.DEV_RUN_PROJECT }}

    # Build and push image to Google Container Registry
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"
    # Deploy image to Cloud Run
    - name: Deploy
      run: |-
        gcloud run deploy "$SERVICE_NAME" \
          --quiet \
          --region "$RUN_REGION" \
          --image "gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA" \
          --platform "managed" \
          --allow-unauthenticated
